### ISSUE TITLE
not functional anymore

### ISSUE THREAD

**Issue by Rasp-lok** [DavideViolante/Linkedin-Feed-Sort-By-Recent#1]
Hey, I just wanted to give a heads up that it doesn't work as it is before.
Nice work

Rasp

**Comment by DavideViolante** [comment]
It seems like they don't use the Cookie anymore to change the feed sort, so this extension is now broken and useless. For now idk how to change the Linkedin default behaviour through a script

**Comment by workproduct** [comment]
is it possible to just have it click the dropdown menu in the interface on load?

**Comment by workproduct** [comment]
https://github.com/workproduct/linkedinRecent

wrote one that did that if you guys are interested

**Comment by DavideViolante** [comment]
That's nice, I didn't think about this because I wanted something permanent, but this is better than nothing, nice job.

**Comment by Rasp-lok** [comment]
> https://github.com/workproduct/linkedinRecent
> 
> wrote one that did that if you guys are interested

Thanks for the response and work-around.

**Comment by DavideViolante** [comment]
LinkedIn finally allowed users to set the feed sorting
![1691053431802](https://github.com/DavideViolante/Linkedin-Feed-Sort-By-Recent/assets/6844116/010322a5-6871-4160-bf9d-0b1f508592d6)

Closing the issue and archiving this repo.
